### ISSUE TITLE
克隆后编译通不过

### ISSUE THREAD

**Issue by gophern** [Amazingwujun/mqttx#1]
有78个编译错误 :(

**Comment by Amazingwujun** [comment]
能否提供编译错误的相关环境和提示呢？
另外项目依赖 lombok ，假如你使用的是 idea ，那么请安装 lombok 的插件。如果还有问题，请详细描述以便我能准确的定位问题

**Comment by Amazingwujun** [comment]
如果你还有问题可以通过邮箱联系我，我远程帮你解决。
