### ISSUE TITLE
Serializer接口有多个实现类，使用的时候提示需要通过 @Qualifier指定实现类，应该指定那个？

### ISSUE THREAD

**Issue by Atomic-AI0** [Amazingwujun/mqttx#13]

**Comment by Amazingwujun** [comment]
mqttx 提供配置项 `mqttx.serialize-strategy` 进行修改, 参考 ***readme*** [6.1 配置项](https://github.com/Amazingwujun/mqttx#61-%E9%85%8D%E7%BD%AE%E9%A1%B9)
