### ISSUE TITLE
这段代码是不是有点低效

### ISSUE THREAD

**Issue by lixin888888** [Amazingwujun/mqttx#2]
Set<String> allTopic = stringRedisTemplate.opsForSet().members(topicSetKey);
        if (CollectionUtils.isEmpty(allTopic)) {
            return Collections.EMPTY_LIST;
        }

        List<ClientSub> clientSubList = new ArrayList<>();
        allTopic.stream()
                .filter(e -> TopicUtils.match(topic, e))
                .forEach(e -> {
                    Map<Object, Object> entries = stringRedisTemplate.opsForHash().entries(topicPrefix + e);
                    if (!CollectionUtils.isEmpty(entries)) {
                        entries.forEach((k, v) -> {
                            String key = (String) k;
                            String val = (String) v;
                            clientSubList.add(new ClientSub(key, Integer.parseInt(val), e));
                        });
                    }
                });

        return clientSubList;

**Comment by lixin888888** [comment]
查出所有的Topic吗

**Comment by Amazingwujun** [comment]
确实存在这个问题，我已尝试加入新的机制来解决它
