### ISSUE TITLE
发布者和订阅者的clientId相同时，订阅者无法接收到消息

### ISSUE THREAD

**Issue by shicy122** [Amazingwujun/mqttx#20]
本地使用模拟器测试发送和接收消息的时候，发布者和订阅者的clientId相同，无法接收到发布者发送的消息，是否考虑支持下这种场景？更多是在测试场景下使用

**Comment by Amazingwujun** [comment]
将配置 `mqttx.ignore-client-self-pub`  改为 false, 就可以收到自己发送的消息了。
> 参考 [配置项说明](https://github.com/Amazingwujun/mqttx#61-%E9%85%8D%E7%BD%AE%E9%A1%B9)

**Comment by shicy122** [comment]
好的，多谢了
