### ISSUE TITLE
能有办法在安卓端运行吗

### ISSUE THREAD

**Issue by imcloud** [Amazingwujun/mqttx#23]
有个局域网群控设备的需求，不知道用这个合适不

**Comment by Amazingwujun** [comment]
适当的对项目代码进行改造应该是可以的

**Comment by songdehuai** [comment]
https://github.com/songdehuai/MoquetteAndroid

**Comment by imcloud** [comment]
> https://github.com/songdehuai/MoquetteAndroid

非常感谢，上个月已经找到了一个
`"io.moquette:moquette-broker:0.16"`

配合这两个成功在安卓平台搭建了一个群控
`
"org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5"
"org.eclipse.paho:org.eclipse.paho.android.service:1.1.1"
`

**Comment by songdehuai** [comment]
这个就是 io.moquette:moquette-broker，我在android11上跑，会用0.16会anr，你没有这个问题吗？

**Comment by Amazingwujun** [comment]
> 这个就是 io.moquette:moquette-broker，我在android11上跑，会用0.16会anr，你没有这个问题吗？

可以将项目改为只依赖 netty, 这不会导致 anr 的问题，至于具体的数据（订阅关系、离线数据）可以使用 sqllite 或直接以内存的形式保存（我记得腾讯开源过一个 mmkv ）
