### ISSUE TITLE
mqttx 由最低支持 jdk1.8 转到 jdk11

### ISSUE THREAD

**Issue by Amazingwujun** [Amazingwujun/mqttx#5]
`jdk11` 比 `jdk8` 还是进化了不少的，尤其是 **ZGC** 的支持， 另外看 **springboot** 对JDK版本的支持，`JDK11` 是大势所趋啊，不知道大家的意见是什么。

**Comment by yuzhuguan** [comment]
应该11

**Comment by Amazingwujun** [comment]
我的格局还是小了，准备直接由 jdk8 升级至 jdk17
