### ISSUE TITLE
你好,有接收和发布的示例代码吗?

### ISSUE THREAD

**Issue by nine-city** [Amazingwujun/mqttx#9]
才接触MQTT,不是很明白
有接收和发布的示例代码吗?
谢谢

**Comment by Amazingwujun** [comment]
客户端代码实现没有实例代码呢😊，如果只是想调试功能，我的建议如下：
调试 mqttx 你需要有客户端才行，网上客户端比较多，建议两种：
1. 下载 **MQTT.fx** 客户端来调试 **mqttx** broker, [下载地址](https://mqttfx.jensd.de/index.php/download)
2. 使用支持 mqtt 协议的 websocket 网页：[mqtt网页调试工具](http://tools.emqx.io)

上面两种客户端不熟悉的话请百度学习使用方式，接下来服务端也有两种方式：
1.  直接使用客户端连接 `mqttx` 云端实例进行测试，方式见:[线上实例](https://github.com/Amazingwujun/mqttx#13-%E7%BA%BF%E4%B8%8A%E5%AE%9E%E4%BE%8B)
2. 自己下载源码搭建环境，参见：[快速开始](https://github.com/Amazingwujun/mqttx#11-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)

还有其它需要可以加入技术交流群来问我

**Comment by nine-city** [comment]
我把配置改成一个公网IP就报错了...
请问要怎么才能订阅到云端服务器的topic
dev配置如下
mqttx:
  web-socket:
    enable: true
  enable-test-mode: true
  host: 139.196.5.207

**Comment by Amazingwujun** [comment]
你应该是自己部署了 mqttx 的服务吧？host 一般情况下不需要手动配置，客户端配置 `ip` 时指定服务器的 `ip` 即可，如果没有前端没有 nginx 之类的负载均衡组件的话。
不知道我理解的对不对?

**Comment by nine-city** [comment]
是的,java脚本放在本地服务器.MQTT服务器放在云服务器上的,现在想订阅云服务器的MQTT的topic,应该要怎么写代码比较好呢

**Comment by Amazingwujun** [comment]
客户端代码？可以参考我开源的项目 [lineyou](https://github.com/Amazingwujun/lineyou)
